### PR TITLE
Add .desktop file

### PR DESCRIPTION
**Pull request by JakobDev**
I currently [create the .desktop file while building](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cubiomes-viewer) in the AUR package. It would be nice, too have it upstream.

### CODE REVIEW

**Comment by Cubitect** [comment]
I'm guessing providing a desktop file would avoid the gendesk for what is essentially a non-changing file.
Is the file name a convention? It seems a little long to me.
Most of the desktop files on my systems are simply named like their program.

**Comment by JakobDev** [comment]
Yes, the name is part of the [specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html):

> The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. The domain name should be followed by the name of the application, which is conventionally written with words run together and initial capital letters (CamelCase). For example, if the owner of example.org writes "Foo Viewer", they might choose the name org.example.FooViewer, resulting in a file named org.example.FooViewer.desktop. 

To be fair, I didn't know about that myself before packing my Programs as Flatpak, where this naming is a requirement. Maybe there should also be a Flatpak package for cubiomes-viewer.

**Comment by Cubitect** [comment]
I think a Flatpak is a good idea, though I haven't used Flatpaks much myself, as I mostly install things as system packages.
Would it be okay to move the .desktop file into a folder (I was thinking maybe `./etc`)?

**Comment by JakobDev** [comment]
> Would it be okay to move the .desktop file into a folder (I was thinking maybe ./etc)?

It's your repo so it's your choice. But I don't think etc is a goof name, since it's the name of the folder who contains all config files. Maybe something like data?

> I haven't used Flatpaks much myself, as I mostly install things as system packages.

I personally prefer system packages too, but Flatpak is great for software developers to provide a easy way to install software for all Linux users. And sometimes theres a Flatpak package for a program that is not in the system repos.

> I think a Flatpak is a good idea,

I can create a Manifest for you, if you want. I have some experience in Flatpak and that would be only 5 Minutes of work for me.

**Comment by Cubitect** [comment]
I was just concerned if it had to be in the root directory for some reason, but I guess it doesn't. `./etc` stands for et cetera, which essentially means 'other things'. It usually contains a lot of configuration, but not exclusively so, and I prefer it over data in this case, since a .desktop file does not seem like 'data' to me.

I should be able to find examples for Qt5 applications that I can reference, so I don't think its necessary, but I won't say no to a more specific reference if you want to make one. In any case I'd like to finish up this next release and maybe make the description of the program a little more informative and possibly tweak the icon a bit, before looking into a Flatpak pr.

**Pull request merged**
